config-version: 2

name: 'quickbooks_source'
version: '0.3.0'
profile: 'bookrqb'

require-dbt-version: ">=0.20.0"

models:
  quickbooks_source:
    +schema: staging
    materialized: table
    tmp:
      materialized: view

vars:
  quickbooks_database: fivetran
  quickbooks_schema: qb_3rdstrt
  quickbooks_source:
    account:                    "{{ source('quickbooks','account') }}"
    address:                    "{{ source('quickbooks','address') }}"
    bill_line:                  "{{ source('quickbooks','bill_line') }}"
    bill_linked_txn:            "{{ source('quickbooks','bill_linked_txn') }}"
    bill_payment_line:          "{{ source('quickbooks','bill_payment_line') }}"
    bill_payment:               "{{ source('quickbooks','bill_payment') }}"
    bill:                       "{{ source('quickbooks','bill') }}"
    bundle_item:                "{{ source('quickbooks','bundle_item') }}"
    bundle:                     "{{ source('quickbooks','bundle') }}"
    credit_memo_line:           "{{ source('quickbooks','credit_memo_line') }}"
    credit_memo:                "{{ source('quickbooks','credit_memo') }}"
    customer:                   "{{ source('quickbooks','customer') }}"
    department:                 "{{ source('quickbooks','department') }}"
    class:                      "{{ source('quickbooks','class') }}"
    deposit_line:               "{{ source('quickbooks','deposit_line') }}"
    deposit:                    "{{ source('quickbooks','deposit') }}"
    estimate:                   "{{ source('quickbooks','estimate') }}"
    estimate_line:              "{{ source('quickbooks','estimate_line') }}"
    invoice_line:               "{{ source('quickbooks','invoice_line') }}"
    invoice_line_bundle:        "{{ source('quickbooks','invoice_line_bundle') }}"
    invoice_linked_txn:         "{{ source('quickbooks','invoice_linked_txn') }}"
    invoice:                    "{{ source('quickbooks','invoice') }}"
    item:                       "{{ source('quickbooks','item') }}"
    journal_entry_line:         "{{ source('quickbooks','journal_entry_line') }}"
    journal_entry:              "{{ source('quickbooks','journal_entry') }}"
    payment_line:               "{{ source('quickbooks','payment_line') }}"
    payment:                    "{{ source('quickbooks','payment') }}"
    purchase_line:              "{{ source('quickbooks','purchase_line') }}"
    purchase:                   "{{ source('quickbooks','purchase') }}"
    purchase_order_line:        "{{ source('quickbooks','purchase_order_line') }}"
    purchase_order:             "{{ source('quickbooks','purchase_order') }}"
    purchase_order_linked_txn:  "{{ source('quickbooks','purchase_order_linked_txn') }}"
    refund_receipt_line:        "{{ source('quickbooks','refund_receipt_line') }}"
    refund_receipt:             "{{ source('quickbooks','refund_receipt') }}"
    sales_receipt_line:         "{{ source('quickbooks','sales_receipt_line') }}"
    sales_receipt:              "{{ source('quickbooks','sales_receipt') }}"
    transfer:                   "{{ source('quickbooks','transfer') }}"
    vendor_credit_line:         "{{ source('quickbooks','vendor_credit_line') }}"
    vendor_credit:              "{{ source('quickbooks','vendor_credit') }}"
    vendor:                     "{{ source('quickbooks','vendor') }}"

    #Variables if your company utilizes the below parent and child transactional tables.
    using_address:        True
    using_bill:           True
    using_credit_memo:    False
    using_department:     True
    using_class:          True
    using_deposit:        True
    using_estimate:       False
    using_invoice:        True
    using_invoice_bundle: False
    using_journal_entry:  True
    using_payment:        True
    using_refund_receipt: True
    using_transfer:       True
    using_vendor_credit:  True
    using_sales_receipt:  True
    using_purchase_order: True

clean-targets:
    - target
    - dbt_modules
 