{% macro get_refund_receipt_columns() %}

{% set columns = [
    {"name": "apply_tax_after_discount", "alias": "apply_tax_after_discount", "quote": true, "datatype": "boolean"},
    {"name": "balance", "alias": "balance", "quote": true, "datatype": dbt_utils.type_float()},
    {"name": "bill_email", "alias": "bill_email", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "billing_address_id", "alias": "billing_address_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "check_payment_account_number", "alias": "check_payment_account_number", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "check_payment_bank_name", "alias": "check_payment_bank_name", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "check_payment_check_number", "alias": "check_payment_check_number", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "check_payment_name_on_account", "alias": "check_payment_name_on_account", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "check_payment_status", "alias": "check_payment_status", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "class_id", "alias": "class_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "created_at", "alias": "created_at", "quote": true, "datatype": dbt_utils.type_timestamp()},
    {"name": "credit_card_amount", "alias": "credit_card_amount", "quote": true, "datatype": dbt_utils.type_float()},
    {"name": "credit_card_auth_code", "alias": "credit_card_auth_code", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "credit_card_billing_address_street", "alias": "credit_card_billing_address_street", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "credit_card_cc_expiry_month", "alias": "credit_card_cc_expiry_month", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "credit_card_cc_expiry_year", "alias": "credit_card_cc_expiry_year", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "credit_card_cctrans_id", "alias": "credit_card_cctrans_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "credit_card_name_on_account", "alias": "credit_card_name_on_account", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "credit_card_postal_code", "alias": "credit_card_postal_code", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "credit_card_process_payment", "alias": "credit_card_process_payment", "quote": true, "datatype": "boolean"},
    {"name": "credit_card_status", "alias": "credit_card_status", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "credit_card_transaction_authorization_time", "alias": "credit_card_transaction_authorization_time", "quote": true, "datatype": "date"},
    {"name": "credit_card_type", "alias": "credit_card_type", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "currency_id", "alias": "currency_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "customer_id", "alias": "customer_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "customer_memo", "alias": "customer_memo", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "department_id", "alias": "department_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "deposit_to_account_id", "alias": "deposit_to_account_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "doc_number", "alias": "doc_number", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "exchange_rate", "alias": "exchange_rate", "quote": true, "datatype": dbt_utils.type_float()},
    {"name": "global_tax_calculation", "alias": "global_tax_calculation", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "home_balance", "alias": "home_balance", "quote": true, "datatype": dbt_utils.type_float()},
    {"name": "home_total_amount", "alias": "home_total_amount", "quote": true, "datatype": dbt_utils.type_float()},
    {"name": "id", "alias": "id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "payment_method_id", "alias": "payment_method_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "payment_reference_number", "alias": "payment_reference_number", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "payment_type", "alias": "payment_type", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "print_status", "alias": "print_status", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "private_note", "alias": "private_note", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "shipping_address_id", "alias": "shipping_address_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "sync_token", "alias": "sync_token", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "tax_code_id", "alias": "tax_code_id", "quote": true, "datatype": dbt_utils.type_int()},
    {"name": "total_amount", "alias": "total_amount", "quote": true, "datatype": dbt_utils.type_float()},
    {"name": "total_tax", "alias": "total_tax", "quote": true, "datatype": dbt_utils.type_float()},
    {"name": "transaction_date", "alias": "transaction_date", "quote": true, "datatype": "date"},
    {"name": "transaction_source", "alias": "transaction_source", "quote": true, "datatype": dbt_utils.type_string()},
    {"name": "updated_at", "alias": "updated_at", "quote": true, "datatype": dbt_utils.type_timestamp()}
] %}

{{ return(columns) }}

{% endmacro %}
